---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: alpine
inputs:
  - name: source
    path: /src
outputs:
  - name: img
run: 
  path: sh
  args: 
    - -exc
    - |
      cd src
      mkdir assets
      yarn build:imgs
      cp -r assets/img ../img