---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
inputs:
  - name: source
    path: /src
  - name: node-modules
    path: /cache
outputs:
  - name: js
run: 
  path: sh
  args: 
    - -exc
    - |
      mv cache/node_modules src
      cd src
      npm run build:js
      cp -r assets/js ../js