---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruken/dutrack-build
inputs:
  - name: source
run:
  path: sh
  args:
  - -exc
  - |
    service postgresql start
    su postgres -c 'psql -c "CREATE DATABASE dutrack;"; psql -c "CREATE USER dutrack PASSWORD '"'dutrack'"'; GRANT ALL ON DATABASE dutrack TO dutrack;"; psql -c "CREATE EXTENSION pgcrypto;" dutrack'
    cd source
    diesel migration run
    cargo build