---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
inputs:
      - name: source
        path: /src
      - name: node-modules
        path: /cache
outputs:
  - name: css
run: 
  path: sh
  args: 
    - -exc
    - |
      cd source
      mv cache/node_modules src
      npm run build:css
      cp -r assets/css ../css