---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: alpine
inputs:
  - name: source
    path: /src
  - name: node-modules
    path: /cache
outputs:
  - name: css
run: 
  path: sh
  args: 
    - -exc
    - |
      mv cache/node_modules src
      cd src
      npm run build:css
      cp -r assets/css/. ../css