resource_types:
- name: npm-cache
  type: docker-image
  source: {repository: ymedlop/npm-cache-resource, tag: latest}

resources:
- name: source
  type: git
  source: &repo
    uri: https://github.com/Rukenshia/dutrack-rs.git
    branch: master
    git_config:
    - name: core.bigFileThreshold
      value: 10m
    disable_ci_skip: true
- name: node-modules
  type: npm-cache # as defined above
  source:
    yarn-support: true
    <<: *repo # the source is the same as the corresponding git resource ...
    paths: # ... except that it's only interested in files listing dependencies
      - package.json

jobs:
- name: cache
  plan:
  - get: source
    trigger: true
  - get: node-modules
- name: assets
  plan:
  - get: source
    trigger: true
    passed: [cache]
  - get: node-modules
    passed: [cache]
  - task: sass_to_css
    file: source/ci/tasks/sass_to_css.yml
  - task: es6_to_js
    file: source/ci/tasks/es6_to_js.yml
- name: rust-build
  plan:
  - get: source
    trigger: true
    passed: [cache]
  - get: node-modules
    passed: [cache]
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "16.04"
      inputs:
        - name: source
      run:
        path: sh
        args:
        - -exc
        - |
          apt-get update && apt-get install -y curl git bash libcurl4-openssl-dev llvm gcc
          curl https://sh.rustup.rs -sSf > install_rustup.sh
          chmod +x install_rustup.sh
          ./install_rustup.sh -y --default-toolchain=nightly
          export PATH="$PATH:$HOME/.cargo/bin"
          cd source
          cargo build