resource_types:
- name: npm-cache
  type: docker-image
  source: {repository: ymedlop/npm-cache-resource, tag: latest}

resources:
- name: source
  type: git
  source: &repo
    uri: https://github.com/Rukenshia/dutrack-rs.git
    branch: master
    git_config:
    - name: core.bigFileThreshold
      value: 10m
    disable_ci_skip: true
- name: node-modules
  type: npm-cache # as defined above
  source:
    yarn-support: true
    <<: *repo # the source is the same as the corresponding git resource ...
    paths: # ... except that it's only interested in files listing dependencies
      - package.json
- name: assets-bundle
  type: s3
  source:
    region_name: eu-central-1
    bucket: dutrack-builds
    versioned_file: assets.tar.gz
    access_key_id: {{aws-key}}
    secret_access_key: {{aws-secret-key}}

jobs:
- name: cache
  plan:
  - get: source
    trigger: true
  - get: node-modules

- name: assets
  plan:
  - get: source
    trigger: true
    passed: [cache]
  - get: node-modules
    passed: [cache]
  - task: sass_to_css
    file: source/ci/tasks/sass_to_css.yml
  - task: es6_to_js
    file: source/ci/tasks/es6_to_js.yml
  - task: copy_images
    file: source/ci/tasks/copy_images.yml
  - task: bundle_assets
    file: source/ci/tasks/bundle_assets.yml
  - put: assets-bundle
    params:
      file: assets-bundle/assets.tar.gz

- name: rust-build
  plan:
  - get: source
    trigger: true
  - task: build
    file: source/ci/tasks/rust_app.yml